### ISSUE TITLE
Inspector window relative size and position to main window is fixed

### ISSUE THREAD

**Issue by FelipeDefensor** [TimeLineAnnotator/desktop#124]
If we have the inspector window open, resizing and/or moving the main window also resizes/moves the inspector window.

https://github.com/FelipeDefensor/TiLiA/assets/87732202/41c529a5-6219-4dfe-ae95-3f2c45511580

**Comment by FelipeDefensor** [comment]
@azfoo this is post v0.3.3. I'm guessing it's related to the latest commits regarding the inspector. Do you have any idea what is going on?

**Comment by azfoo** [comment]
I doubt it is a bug related to anything recent, but a feature of QDockWidget. Unlike an actual window, it is linked to the parent QMainWindow. Switching from QDockWidget to QDialog or some other type of window could potentially fix this.

**Comment by FelipeDefensor** [comment]
I double checked and this has been going since at least v0.3, actually. I'm very surprised I didn't notice this before.

I would like to keep this as a QDockWidget because the docking seems like a desirable feature for this case.

Let's take a look at this once we have the time.

**Comment by FelipeDefensor** [comment]
924001399043c9ce038b7b4eef3aa93268576516 makes this a non-issue by docking the inspector permanently. 

It In the future, it would be good to have the option to undock the inspector and not get this weird behavior. It seems won't be possible to inherit from `QDockWidget` for that, which means we would have to implement a good part of the docking behavior ourselves.
