### ISSUE TITLE
Can't reopen PDF or video windows if they are closed by the OS

### ISSUE THREAD

**Issue by azfoo** [TimeLineAnnotator/desktop#148]
I suggest that we create a "View" menu in the main menu bar where users can toggle the visiblity of those windows and of the Inspect window.

**Comment by azfoo** [comment]
There is a hacky solution of making the pdf and video windows subwindows instead, so they don't show up on the start bar and are not technically closeable by the os. The downside is that subwindows are not minimisable which might be a nice feature to have. Will go ahead and implement your suggestion anyway.

**Comment by FelipeDefensor** [comment]
That would be nice, but minimizing is a must for the cases where the user is just interested in the audio of a YouTube video.
