### ISSUE TITLE
Warn user that loading media failed when opening file

### ISSUE THREAD

**Issue by azfoo** [TimeLineAnnotator/desktop#153]
The current result is a silent fail. Notice that the media length is "loaded" nevertheless and that is by design, so the timelines can still be displayed even before loading a new media.

**Comment by azfoo** [comment]
Not a silent fail since #132. Player is disabled since no media is loaded so crashes due to no media are prevented. Tooltip on disabled player requests user to load media.

**Comment by FelipeDefensor** [comment]
The user might not hover the button for long enough to actually see the tooltip. I think an error message at the time of loading in addition to the tooltip is better.

Also, the tooltip is only being displayed on the stop button:

https://github.com/TimeLineAnnotator/desktop/assets/87732202/516ceda7-915e-4f2a-8fe1-32037067bd9d
