### ISSUE TITLE
Missing a save button in the metadata window

### ISSUE THREAD

**Issue by FelipeDefensor** [TimeLineAnnotator/desktop#182]
Currently, the only way to save is to confirm the dialog when trying to close, which is counterintuitive. We could without the save button if changes were autosaved, but hen we would need a discard button.

**Comment by azfoo** [comment]
We could have it like the settings window where there are the apply (save edits without closing) and cancel (don't save, just close) buttons.

**Comment by FelipeDefensor** [comment]
> We could have it like the settings window where there are the apply (save edits without closing) and cancel (don't save, just close) buttons.

Yes, I like that.
