### ISSUE TITLE
PDF window names are not very helpful when there are multiple PDF timelines

### ISSUE THREAD

**Issue by FelipeDefensor** [TimeLineAnnotator/desktop#190]
The screenshot shows that the first PDF window gets 'TiLiA PDF Viewer' as a name and the remaining get the media title as a name.

![image](https://github.com/user-attachments/assets/a625e5ce-eea0-43b4-8567-56a0901f0b54)

With that naming, it's impossible to tell which PDF window we are toggling when using the menu. The user has to go through some trial-and-error to close/open a specific window.

**Comment by FelipeDefensor** [comment]
@azfoo, I believe we have already talked about the naming on the windows. Having them named "TiLiA PDF Viewer" is what we want for the OS window manager, but in our UI we need names that indicate which timelines they belong to.

Could you take a look at this?

**Comment by azfoo** [comment]
Sorry, I cannot reproduce this. But to help with debugging, is the window title of the pdf linked to 'PDF Viewer' also 'PDF Viewer' and not the title of the document?
