### ISSUE TITLE
HierarchyTimeline: Slider obstructs hierarchy levels (with 6 or more levels)

### ISSUE THREAD

**Issue by johentsch** [TimeLineAnnotator/desktop#201]
Example file (rename to `example.tla`): [example.json](https://github.com/user-attachments/files/17369461/example.json)

To reproduce, raise any of the top nodes by any number of levels.

**Comment by FelipeDefensor** [comment]
It is not so much that the slider is obstructing the remaining levels, as that the timeline is not tall enough to display all levels. You can fix that by right click an empty area in the timeline selecting "Change height" and providing a larger height.

**Comment by FelipeDefensor** [comment]
What would be better is for the app to automatically increase the timeline height if the a new level would be obstructed, as in your example. That's already on the roadmap and should be implemented for v0.5.
