### ISSUE TITLE
Convenient way needed to open and close "Inspect" menu (or rather, to label a component)

### ISSUE THREAD

**Issue by johentsch** [TimeLineAnnotator/desktop#203]
**Desired behaviour**

Double-click on the component of a hierarchy or use a hotkey to open the "Inspect" mask in order to label it and/or assign a function or type. Press `Enter` or `Esc` to close it.

**Current behaviour**

No hotkeys are assigned. One needs to right-click and select "Inspect". The only way to close the mask is using the mouse (or the OS's hotkey to close the window which is not suited for a "confirm" action).

**Discussion**

Alternatively, and maybe even more desirable, the user could simply start typing to label a component (which would require adding `Ctrl/Cmd` to the hotkeys which are currently single-key). A good example for this straightforward way of labelling things is https://draw.io Considering the importance of labels in an annotation app, I reckon it would be worth the change. A streamlined way to annotate with keyboard only is would be a killer feature IMHO.

**Comment by FelipeDefensor** [comment]
> Alternatively, and maybe even more desirable, the user could simply start typing to label a component (which would require adding Ctrl/Cmd to the hotkeys which are currently single-key). A good example for this straightforward way of labelling things is https://draw.io/ Considering the importance of labels in an annotation app, I reckon it would be worth the change. A streamlined way to annotate with keyboard only is would be a killer feature IMHO.

I need to sleep on this as this is a major UI change, but it strikes me as a great improvement.

> Double-click on the component of a hierarchy or use a hotkey to open the "Inspect" mask in order to label it and/or assign a function or type. Press Enter or Esc to close it.

Completely agree and should be easy to implement. Don't know if you realized, but you can already use Enter to open the "Inspect" dialog, but not to close it.

**Comment by FelipeDefensor** [comment]
> Alternatively, and maybe even more desirable, the user could simply start typing to label a component (which would require adding Ctrl/Cmd to the hotkeys which are currently single-key). A good example for this straightforward way of labelling things is https://draw.io/ Considering the importance of labels in an annotation app, I reckon it would be worth the change. A streamlined way to annotate with keyboard only is would be a killer feature IMHO.

@azfoo could you weigh in on this? I have given it some thought and I am inclined to go for it.

**Comment by azfoo** [comment]
Don't see why not!
Alternatively, I'm thinking it would be easiest if we just set the focus on the label in the inspector instead, so you could do "<enter> <label text> <enter?>". That would just need a simpler way of closing the inspector with a keypress.

**Comment by FelipeDefensor** [comment]
> Alternatively, I'm thinking it would be easiest if we just set the focus on the label in the inspector instead, so you could do " <enter?>". That would just need a simpler way of closing the inspector with a keypress.

That should already be a significant improvement. Let's implement that right away and give some thought to the more radical option, then.

**Comment by azfoo** [comment]
Will work on it!

**Comment by azfoo** [comment]
At some point, a shortcuts page will be made with all of the available shortcuts and what they do.
