### ISSUE TITLE
Allow for annotating beat grid without media

### ISSUE THREAD

**Issue by johentsch** [TimeLineAnnotator/desktop#218]
**Desired behaviour**

Open TiLiA, create beat grid, start annotating.

**Current behaviour**

Adding beat grid fails with `Cannot create timeline with no media loaded`.

**Discussion**

This is probably part of a bigger issue which is lacking convenience in creating and editing beat grids. Like, when someone enters a grid as numbers, it could be generated right away by distributing beats evenly (as a reasonable default). In my view, the whole functionality of aligning audio with symbolic timelines is huge and involves quite a few slippery slopes, but on the other hand, good solutions already exist for many of them (e.g. in the context of the [match format]([https://doi.org/10.17613/37mm-pt05](https://hcommons.org/deposits/item/hc:59273))). I saw that you can import the beatgrid from CSV so probably you have already thought about creating compatibility with the Sonic Visualizer?

I think this topic warrants important conceptual work for the planned inclusion of scores.

**Comment by FelipeDefensor** [comment]
Being able to create a timeline without loading a media is something that we should implement, yes. That would amount to creating a king of "abstract" player, which should be straightforward. A temporary work-around would be to create a file in CLI and use the `set-media-length` command to set a dummy length, save it, and then open it in the GUI. Additionally, one might import a CSV with evenly spaced beats in either the CLI or the GUI to get a beat grid.

I think I see what you mean reagarding the scores. When a score timeline is in place it will make even more sense to not require loading a media to begin annotating, as some users might want to annotate "directly" on the score. I imagine that might be your case. Given that, I will make sure those two functionalities are released simultaneously. Also, having an obvious way to create an even beat grid would fit right in.

I may be underestimating the task of aligning symbolic notation with audio, but then again, the hard part is something I expect the user to have done, that is, to have properly aligned the beats in a beat timeline with the audio/video and also to have set measure numbers that match the source they intend to use. Given that, I don't think there's anything that could go *too* wrong. I'm not familiar with the match format, please do explain if you think it is worth it.

**Comment by FelipeDefensor** [comment]
Feature has been merged and will be released on v0.5.
